# Generated by Django 5.0.5 on 2025-01-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_creditrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
