# Generated by Django 5.0.5 on 2025-01-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_name',
            field=models.CharField(choices=[('youtube_like', 'YouTube Like'), ('youtube_sub', 'YouTube Subscribe'), ('youtube_view', 'YouTube View')], max_length=20),
        ),
    ]
